### ISSUE TITLE
windows平台下，样式文件mime不对

### ISSUE THREAD

**Issue by zituocn** [codeskyblue/gohttpserver#1]
我的系统是windows 2008 R2
样式文件不能正常浏览，会提示下载。

**Comment by codeskyblue** [comment]
css吗？

**Comment by codeskyblue** [comment]
刚试了试还可以呀
![image](https://cloud.githubusercontent.com/assets/3281689/17285773/868c8026-57f7-11e6-87bf-f22b4778e67d.png)

**Comment by zituocn** [comment]
我这是2008 R2，确实不行。之前无闻的gogs也有同样的问题，后面恢复了。也许是系统问题吧。
前台样式出不来，直接浏览样式文件，是下载。我这的response headers里，只有一个data属性。

**Comment by codeskyblue** [comment]
感觉就是系统问题
