### ISSUE TITLE
文件如果含有 # 會發生問題

### ISSUE THREAD

**Issue by mao-shonen** [codeskyblue/gohttpserver#11]
文件如果含有 # 會發生問題

**Comment by codeskyblue** [comment]
会发生什么问题？

**Comment by codeskyblue** [comment]
不是很想处理这个issue，不过很欢迎pr

**Comment by mao-shonen** [comment]
如果進入 www.myhome..com/A#123 這個目錄
會被導向至 www.myhome..com/A#123/A#123 但是實際上並沒有進入
再次點擊會變成 www.myhome..com/A#123/A#123/A#123 一樣沒有進入
文件跟文件夾都會發生

**Comment by adolli** [comment]
这么说的话，包含问号也会。求修复

**Comment by hoogw** [comment]
I know this # issue. 

I just try NOT use # in file name or folder name, it solve the problem .

**Comment by hoogw** [comment]
This is a good bug, if I don't want people see some folder, I will make folder name as '#xxxxxxxx', it means hidden folder, hidden file.......

**Comment by adolli** [comment]
@hoogw aHa, this bug is becoming a handy feature!
