### ISSUE TITLE
Does it support Raspberry Pi system? Thank you

### ISSUE THREAD

**Issue by ErikZhou** [codeskyblue/gohttpserver#114]
Does it support Raspberry Pi system? Thank you

**Comment by Herts** [comment]
Yes, try arm64 version: [gohttpserver_1.1.0_linux_arm64.tar.gz](https://github.com/codeskyblue/gohttpserver/releases/download/1.1.0/gohttpserver_1.1.0_linux_arm64.tar.gz)

**Comment by Darthagnon** [comment]
Usually, it's ```armhf``` or ```armv7``` linux builds that work on Raspberry Pi (I have a Pi 3). Don't know if that's different with the Pi 4.
