### ISSUE TITLE
为了防止滥用，我该如何禁用全局搜索，zip下载等功能

### ISSUE THREAD

**Issue by huangguiniab** [codeskyblue/gohttpserver#116]
如题，我想把我的文件服务器开放出来公用，若是有人滥用使用搜索功能和zip打包下载，我的服务器压力会很大的，我该如何设置呢

**Comment by codeskyblue** [comment]
gohttpserver设计之初其实就是为了小规模使用的，当初就没计划大规模使用

**Comment by molixiaoge** [comment]
同有这个需求，能不能添加个选项禁止zip下载
