### ISSUE TITLE
/分隔符显示不正常

### ISSUE THREAD

**Issue by xtutu** [codeskyblue/gohttpserver#137]
## 用 docker 方式运行
```bash
sudo docker run -p 61206:8000 -v /volume1/docker/http-server/data:/app/public -d --restart=always --name httpserver codeskyblue/gohttpserver --upload --delete
```

## 目录结构
```bash
$ tree
.
├── config.yml
└── data
    └── ProjectList
        └── S
```

## 浏览器显示
![image](https://user-images.githubusercontent.com/12950709/145386374-99b7c878-fe6d-4a9e-a990-5d600308b277.png)

![image](https://user-images.githubusercontent.com/12950709/145388367-b0155f3c-fba2-4eaf-99d9-ec6ca6a98a0d.png)

**Comment by xguo-prestolabs** [comment]
我也碰到同样的问题
