### ISSUE TITLE
How to upload file programmatically? 

### ISSUE THREAD

**Issue by powof2** [codeskyblue/gohttpserver#139]
Hi there,
How to upload file programmatically with POST? like [this](https://stackoverflow.com/questions/21781831/android-upload-of-file-to-server).
The HTTP Response is 200, but no file is uploaded.

thank you.

**Comment by NiceGuyIT** [comment]
Hey. I had the same need and wrote a client for gohttpserver: [go-go-files](https://gitlab.com/NiceGuyIT/go-go-files) You can upload, download and search for files on the server.

**Comment by powof2** [comment]
Hi NiceGuyIT,

This is great! thank you.

Or even better, can this be ported to Java or C/C++? im not familiar with the Go lang. (I can handle simple Java programming though).

My use case is like this (Android): upload local progress file (.save or whatever saved as game progress) to PC, so i can test the PC version of the App on Desktop without having to connect my phone.

Maybe ported to C/C++ is better? because the App also works on iOS.

Do you think it is possible to compile your work as dynamic library (.so on Android and .a on iOS), this way there will be no more porting jobs.

Thank you.

**Comment by NiceGuyIT** [comment]
Hi powof2,

My tool is meant to be a configureless automation tool. As such, it won't have a GUI that mobile apps need.

If you're looking to move files between mobile and desktop, check out [Syncthing](https://syncthing.net/). It allows you to sync a folder between two devices similar to Dropbox, Google Drive, etc. The Android app is on Google Play and F-Droid.

iOS is another story, however, as you'll have to pay the Apple tax. Many [open source] developers have tried only to discover it's a paywall. Take Gotify for instance with this [comment](https://github.com/gotify/server/issues/87#issuecomment-457453135). (Well not technically a paywall but goes against their "100% open source solution" they are developing.)

Now there are Apple apps that support the Syncthing protocol. [Möbius Sync](https://apps.apple.com/us/app/m%C3%B6bius-sync/id1539203216) for example. I haven't used it so I can't speak as to how well it works.

Have a nice day!

**Comment by powof2** [comment]
Hi NiceGuyIT,

Thanks for the suggestions.

I can upload my .save file to desktop via opera (or maybe Firefox, Chrome), but it takes many clicks, it works anyway so i'll stick with opera.

I can also base64 my .save file (it's small) and send it via mail to desktop, this way it will work on both iOS and Android but for now it's not necessary yet.
