### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by thincal** [codeskyblue/gohttpserver#14]
由于只有一个域名abc.example.com，我想让 http://abc.example.com/fileserver 来指向这个gohttpserver，请问gohttpserver需要做什么修改来支持？谢谢。

**Comment by codeskyblue** [comment]
不太好搞？

**Comment by codeskyblue** [comment]
不如新开一个二级域名来的简单

**Comment by codeskyblue** [comment]
先关掉了
