### ISSUE TITLE
请问一下，可以修改标题栏么？

### ISSUE THREAD

**Issue by gkgx163** [codeskyblue/gohttpserver#147]
![image](https://user-images.githubusercontent.com/59253327/169684184-fb527b92-ff8b-4c5d-a01c-372acf2d45d5.png)
在这里修改成自己想要的名称。
谢谢。

**Comment by codeskyblue** [comment]
gohttpserver --title "Your title here"

**Comment by gkgx163** [comment]
这是啥意思啊？没看懂

**Comment by gkgx163** [comment]
> gohttpserver --title "Your title here"

这是啥意思啊？没看懂

**Comment by codeskyblue** [comment]
命令行参数呀
