### ISSUE TITLE
建议上传下载使用分片完成

### ISSUE THREAD

**Issue by liutt1312** [codeskyblue/gohttpserver#155]
在网络不稳定，上传或下载文件错误；在传输大文件是就会出现错误的情况，使用分片传输应该可以解决或改善这个问题

**Comment by codeskyblue** [comment]
上传可以分片，之前试着弄过，没整完。
下载没必要分片，一般的下载软件都有继续下载的功能。

**Comment by liutt1312** [comment]
分片上传还是很有必要的，上传很容易错误（网络不好或大文件上传），加油

**Comment by dfengpo** [comment]
请问分版上传解决了吗
