### ISSUE TITLE
Does version 1.1.4 support chunked upload? 

### ISSUE THREAD

**Issue by roderick6668** [codeskyblue/gohttpserver#163]
If use Cloudflare to proxy gohttpserver, there is a 100MB upload file size limited. 
Check here(https://developers.cloudflare.com/cache/about/default-cache-behavior)

I know somebody mentioned chunked upload before in the issue session, but I used CF to proxy my gohttpserver(v1.1.4). I can't upload any file size larger than 100MB. So I assume gohttpserever hasn't chunked the upload.

**Comment by codeskyblue** [comment]
not yet
