### ISSUE TITLE
Command not found / Comando não encontrado

### ISSUE THREAD

**Issue by hahndouglasf** [codeskyblue/gohttpserver#168]
Hello everyone, maybe it's something silly, but I'm getting feedback; gohttpserver: command not found.
Could you let me know what is going on? and how to fix it?

Olá a todos, talvez seja algo bobo, mas estou recebendo feedback; gohttpserver: comando não encontrado.
Alguém poderia me informar o que está acontecendo? e como consertar isso?

![image](https://user-images.githubusercontent.com/91286300/212753155-4979a3fb-0a5c-42cb-bf3d-a960d75fea45.png)

**Comment by WeskerC** [comment]
same problem here
