### ISSUE TITLE
Suport Strikethrough Wanted

### ISSUE THREAD

**Issue by icewukong** [codeskyblue/gohttpserver#18]
Strikethrough in markdown file seemingly unsupported

**Comment by codeskyblue** [comment]
for example?

**Comment by icewukong** [comment]
Wanted this: ~~asdfasdfasdf~~ ,but in gohttpserver, it is displayed as: `~~asdfasdfasdf~~`

**Comment by codeskyblue** [comment]
wow, learn knew things.

**Comment by codeskyblue** [comment]
Note: need to update showdown to the lastest version
