### ISSUE TITLE
带中文路径生成二维码，扫描会出现乱码url

### ISSUE THREAD

**Issue by chenlongwill** [codeskyblue/gohttpserver#19]
修正res/js/index.js
genQrcode: function(text, title) {
      var urlPath = this.genInstallURL(text);
      var str = urlPath;
      var arr = str.split("/");
      arr[arr.length - 1] = encodeURI(arr[arr.length - 1]);
      var dir = arr.join("/");
      $("#qrcode-title").html(title || text);
      $("#qrcode-link").attr("href", urlPath);
      $('#qrcodeCanvas').empty().qrcode({
        text: dir
      });
      $("#qrcode-modal").modal("show");
    },

**Comment by codeskyblue** [comment]
Thanks, I'll fix it tomorrow
