### ISSUE TITLE
监听443端口和80端口

### ISSUE THREAD

**Issue by wzhy90** [codeskyblue/gohttpserver#21]
自己申请了个证书，然后启动的时候加上证书参数并监听443端口，浏览器直接用https加域名可以访问，但是如果直接域名访问浏览器会默认访问80端口，然后服务器只监听了443端口所以没办法自动跳转到443。能做一个https模式同时监听443和80吗？监听到80有链接就跳到443

**Comment by codeskyblue** [comment]
最好还是nginx 反向代理吧

**Comment by wzhy90** [comment]
好的，了解了
