### ISSUE TITLE
进入文件夹后左上角二维码点view地址问题

### ISSUE THREAD

**Issue by wzhy90** [codeskyblue/gohttpserver#22]
会在当前地址后面再加文件夹名字。但是当前地址已经包含了文件夹名字了
无语了，不知道为啥传不到图，我晚上回去再传吧

**Comment by wzhy90** [comment]
![qq 20170720120940](https://user-images.githubusercontent.com/2318890/28447657-c7340ee0-6e04-11e7-880f-a3eb85da2c1b.png)

**Comment by codeskyblue** [comment]
看不懂，能不能再描述的清楚点

**Comment by wzhy90** [comment]
就是我本来的路径就只有会计这个的，但是在二维码窗口右上角点View的话打开的路径就变成了两个会计

**Comment by codeskyblue** [comment]
Sorry for the delay, fixed in current version.
