### ISSUE TITLE
openID问题，国内有什么服务商提供这个？

### ISSUE THREAD

**Issue by wzhy90** [codeskyblue/gohttpserver#23]
腾讯跟微博的都是OAuth2这种，好像并不兼容openID。还有什么其他的供应商吗？

**Comment by codeskyblue** [comment]
你提个pr加一下？

**Comment by wzhy90** [comment]
不懂啊，所以好像国内真没啥openID的，你代码里默认的网易好像是内部用的

**Comment by codeskyblue** [comment]
外部我就保留了一个 HTTP简单的用户名密码认证

**Comment by codeskyblue** [comment]
issue关掉了，回头加上个oauth2的认证
