### ISSUE TITLE
上传文件大于500k 时报 java.net.SocketException: Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by gravin** [codeskyblue/gohttpserver#24]
httpClient = HttpClients.custom().setDefaultCredentialsProvider(provider).build();

            MultipartEntityBuilder builder = MultipartEntityBuilder.create();
            File file=new File(fileName);
            builder.addBinaryBody("file",file,ContentType.APPLICATION_FORM_URLENCODED,file.getName());

            HttpEntity reqEntity = builder.build();
            httpPost = new HttpPost(serverUrl);
            httpPost.setEntity(reqEntity);
            response = httpClient.execute(httpPost);

**Comment by codeskyblue** [comment]
看不懂Java，不过我确定上传是没有问题的

**Comment by codeskyblue** [comment]
长期没有反馈，先关闭了
