### ISSUE TITLE
Run on android & ios

### ISSUE THREAD

**Issue by lunny** [codeskyblue/gohttpserver#3]
Could you provide some releases for windows, linux, mac or android & ios? And also, you can provide a qr code to help mobile phone to visit your file server.

**Comment by codeskyblue** [comment]
终于见到lunny大神，编译后的我放到release下了，虽然有点滞后。恩，供手机使用的qrcode有点意思，我打算先放到nav里面。明天整整

**Comment by codeskyblue** [comment]
ios的编译不出来呀

**Comment by codeskyblue** [comment]
安卓的版本倒是可以有

**Comment by codeskyblue** [comment]
不过没多大用途呀

**Comment by lunny** [comment]
我的意思是你用Go语言和gomobile开发一个ios和android的app，渲染一个qrcode出来，用这个在两个手机之间共享文件很方便啊。

**Comment by codeskyblue** [comment]
这个不搞不搞，因为已经有好多这种了，什么快传了，无限wifi啦，这种应用多的很
