### ISSUE TITLE
Migrate frontend to vue spa ?

### ISSUE THREAD

**Issue by gengjiawen** [codeskyblue/gohttpserver#30]
This will help to make the dependencies and code a lot cleaner.

**Comment by codeskyblue** [comment]
this one? https://github.com/skyronic/vue-spa

**Comment by gengjiawen** [comment]
The official one using webpack https://github.com/vuejs-templates/webpack.

**Comment by gengjiawen** [comment]
We may lose seo if we don't use ssr though.

**Comment by codeskyblue** [comment]
sorry? I dont understand "ssr", what is this?

**Comment by gengjiawen** [comment]
https://vuejs.org/v2/guide/ssr.html.

**Comment by codeskyblue** [comment]
Seems not a good idea to use ssr, since this project is go backends.

**Comment by gengjiawen** [comment]
But we can still use spa with no ssr support.
