### ISSUE TITLE
can I search file by name?

### ISSUE THREAD

**Issue by hoogw** [codeskyblue/gohttpserver#45]
I try to search file by file name, (NOT text contend inside file). 
I want to find all file name, that have "xxxx", but nothing return.

How to use the search box on top right corner?

Can you wrote some details in READ ME, teach us how to use search function?

**Comment by codeskyblue** [comment]
this is too simple, just like normalwindow file browser search

**Comment by hoogw** [comment]
Thanks for answering my question. 
There are something I don't understand. 
Can I ask more about this?

You mean use ctrl + F on browser, to find file name?

It works, but I want to find the file under the subfolder, 
if I have a file yyy.txt at:     /deep1/deep2/deep3/yyy.txt

On home page, I hope to search for 'yyy', then find it . 
How I do this?
