### ISSUE TITLE
rest api feature?

### ISSUE THREAD

**Issue by hoogw** [codeskyblue/gohttpserver#46]
Is it possible add new feature as rest api?

for example:

http://localhost:8000/xxx?f=json

this url will response as a json instead of html.

`      {
   subfolder: {
                 { folder: xxxx1},                
                  { folder: xxxx1}         
                },

   file: {
              {file: yyy1},
              {file: yyy2}
              .....
        }

}`

you also can add other meta data info into this json. 

Why do  this, is because if you have this rest api,  I can write page easy search file name(since all file name, file info are in Json format.)

I mean, you have build the website, if you add rest api for this web site, will be very useful for third party wrote apps to communicate with your site. 

For example, twitter rest api,   facebook rest api, flickr rest api. etc......

**Comment by hoogw** [comment]
http://localhost:8000/xxx?f=json  

return json

http://localhost:8000/xxx

return regular html(just like it is now)

**Comment by codeskyblue** [comment]
try to use chrome debug tools to see the rest api.

**Comment by hoogw** [comment]
Perfect, well done. 

[http://xxxxx.com:8000/-/json/?_=1545072048246](http://transparentgov.net:8000/-/json/?_=1545072048246)


will give you a nice json response. as 
nice and well done. 

`

{
  "auth": {
    "upload": false,
    "delete": false,
    "users": null,
    "AccessTables": null
  },
  "files": [
    {
      "name": "City of Costa Mesa",
      "path": "City of Costa Mesa",
      "type": "dir",
      "size": 58084919,
      "mtime": 1544829343544
    },
    {
      "name": "Los Angeles County Public Work/landrecords",
      "path": "Los Angeles County Public Work/landrecords",
      "type": "dir",
      "size": 678440673,
      "mtime": 1544827660045
    },
    {
      "name": "Los Angeles County Regional Planning",
      "path": "Los Angeles County Regional Planning",
      "type": "dir",
      "size": 638026825,
      "mtime": 1544816016211
    },
    {
      "name": "Los Angeles Public Work/Bureau of Engineering",
      "path": "Los Angeles Public Work/Bureau of Engineering",
      "type": "dir",
      "size": 21696026490,
      "mtime": 1544824661671
    },
    {
      "name": "config.yml",
      "path": "config.yml",
      "type": "file",
      "size": 90,
      "mtime": 1544816316334
    }
  ]
}

`

**Comment by hoogw** [comment]
The response json have path, it is full path relative to home, very nice, well done. 

`{
  "auth": {
    "upload": false,
    "delete": false,
    "users": null,
    "AccessTables": null
  },
  "files": [
    {
      "name": "Annexation",
      "path": "City of Costa Mesa/Annexation",
      "type": "dir",
      "size": 2810296,
      "mtime": 1544829343447
    },
    {
      "name": "general",
      "path": "City of Costa Mesa/general",
      "type": "dir",
      "size": 55274623,
      "mtime": 1544829344940
    }
  ]
}`
