### ISSUE TITLE
file name with '&', failed to load  

### ISSUE THREAD

**Issue by hoogw** [codeskyblue/gohttpserver#49]
some time, user just use special char, like &, #, @, etc.... as file name. 

then failed to load those files. 

Please advice a way to work around?

**Comment by hoogw** [comment]
Recommend if you can fix this issue. 
Why?
Some of my user, client, they want to use special char as file name. 
If hundreds of thousands user,  impossible to tell them to NOT use special char. 

Any special char is  valid in  windows, linux file system, it should be valid in here as well.

**Comment by codeskyblue** [comment]
Mac上并未发现该问题。
