### ISSUE TITLE
why search file does not works for me?

### ISSUE THREAD

**Issue by hoogw** [codeskyblue/gohttpserver#50]
I try the demon [https://gohttpserver.herokuapp.com](https://gohttpserver.herokuapp.com)

on right top corner, search text box, I type 'readme' it only works one time. 

then it stop  working. 

Then I try type  'image.jpg' in search box right top corner, then nothing. This file is under 'filetypes' folder, why it not find?

Can you advise, why, this happen to me?

**Comment by codeskyblue** [comment]
sorry, it works for me

**Comment by hoogw** [comment]
I try opera, IE edge, firefox, chrome,  None of them works. 
When I click search 'test', no https request send out,  this is NOT right,  should see https request send out. 

when click search button, nothing happen. 
https://gohttpserver.herokuapp.com

But only 1 time it works, no error on console,  what browser you use? Or it is only works in china?

**Comment by hoogw** [comment]
I figure out, the search icon, is broken. not sure why?

If I type 'xxx' at search box top right corner, then click enter, the search works fine. 
But if I click the search icon with magnify glass icon, nothing happen. 

So need to fix the search icon, attach it to search event.

**Comment by hoogw** [comment]
Ok, spend 6 hours , finally fix this problem. 

This is vue version 1, not 2,  so you need to be aware. 

The search icon isn't working, you have to do below steps to make click search icon works:

index.js 
   add function under method:{}

        ` methods: {

       // ------------ search icon clicked event ----------------
         
              search_clicked: function (event) {
                // `this` inside methods points to the Vue instance
              // alert('Hello ' + this.search + '!')
              
              
                  var searchParams = new URLSearchParams(window.location.search)
                  searchParams.set("search", this.search);
       
        
                  // this cause reload  https://stackoverflow.com/questions/5999118/how-can-i-add-or-update-a-query-string-parameter
                  //window.location.search = searchParams.toString();

                // to avoid reload
                // var newRelativePathQuery = window.location.pathname + '?' + searchParams.toString();
                //history.pushState(null, '', newRelativePathQuery);

                // here I do want reload, so must use this.
                window.location.search = searchParams.toString();
                
                // no need this, because last line already cause reload.
                // location.reload();
                    
                    // `event` is the native DOM event
                    if (event) {
                    // alert(event.target.tagName)

        }
      },`


index.html page, replace search input and icon with this

              ` 

            <span class="input-group-btn">
              <button class="btn btn-default" type="button" v-on:click="search_clicked">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </span>

            
              <input type="text" name="search" class="form-control" placeholder="Search" v-model="search"
              autofocus>
`

**Comment by hoogw** [comment]
without fix the search icon, you have to click enter key to be able to search. 
if you only click search icon, nothing happen. 

if you want to make search icon works as well, you have to make 2 change as above I showed you.

**Comment by codeskyblue** [comment]
Sorry for the delay.
