### ISSUE TITLE
How to setup https(ssl)?

### ISSUE THREAD

**Issue by hoogw** [codeskyblue/gohttpserver#51]
I see your code support https, but I am not sure, how and where,
can you write more details how and where on README?
I know this is go and https question, should not be here, 
but since your code already support https, your simple a few words will helps alot.

What I don't know is where to setup gcfg.Cert, gcfg.Key?

I have 2 files "public.cert" and  "private.key"
where should I put these 2 files for https, 

And does config.yml need to update?
 how to connect gcfg.Cert, gcfg.Key to those 2 files?
 

I also try 

        gcfg.Cert = "./public.cert"
	gcfg.Key = "./private.key"

and put those 2 files at ./ , failed. 

       var err error
	if gcfg.Key != "" && gcfg.Cert != "" {
		err = http.ListenAndServeTLS(gcfg.Addr, gcfg.Cert, gcfg.Key, nil)
	} else {
		err = http.ListenAndServe(gcfg.Addr, nil)
	}
	log.Fatal(err)

**Comment by hoogw** [comment]
I know why, 

when I run it, I use:
                       `gohttpserver -r ./fileRestAPI --cors`  

this somehow did not pick up any change I made at main.go file. 

Instead you should use ./

                 `./gohttpserver -r ./fileRestAPI --cors`

**Comment by hoogw** [comment]
I successfully made https, share it here, 

First I copy and past 2 file "public.cert", "private.key" to 
          `... go\src\github.com\codeskyblue\gohttpserver`




Then update main.go. 


    var err error
	if gcfg.Key != "" && gcfg.Cert != "" {
		err = http.ListenAndServeTLS(gcfg.Addr, gcfg.Cert, gcfg.Key, nil)
		 
		//err = http.ListenAndServeTLS(gcfg.Addr, "public.cert", "private.key", nil)

	} else {

		//err = http.ListenAndServe(gcfg.Addr, nil)
		err = http.ListenAndServeTLS(gcfg.Addr, "public.cert", "private.key", nil)
       
	}


then:  

        go build

run it:    
                ` ./gohttpserver -r ./fileRestAPI --cors`

Note:
              `You must use ./  at beginning ./gohttpserver   , otherwise, updated main.go change will NOT get picked up, this cause me 4 hours to figure out here. `

**Comment by codeskyblue** [comment]
Recommend use nginx to proxy pass gohttpserver, and manage https certificate with nginx.
