### ISSUE TITLE
how to run it on linux as background?

### ISSUE THREAD

**Issue by hoogw** [codeskyblue/gohttpserver#52]
Lots of friends have same issue, I spend 5 hours to figure it out, just share with friends here. 

// run it as background

// create file, save to where you call gohttpserver folder.

// create config file

// use nano to edit, or you can create it at windows, use winSCP to copy over 
        `nano supervisord.conf`

// type content
       `[program:supervisord]
          command=./gohttpserver -r ./fileRestAPI  --cors`

If you want to save the changes you've made, press Ctrl + O. 
To exit nano, type Ctrl + X. If you ask nano to exit from a modified file, it will ask you if you want to save it. 
Just press N in case you don't, or Y in case you do. It will then ask you for a filename. 
Just type it in and press Enter.

//start supervisord

         supervisord -c supervisord.conf

//stop supervisord
// first switch to root user
    `sudo su`
     cd /home/hoogw/gowork/src/github.com/codeskyblue/gohttpserver

https://stackoverflow.com/questions/14479894/stopping-supervisord-shut-down
      `ps -ef | grep supervisord`
       `kill -s SIGTERM 15923 `   ( only one number a line , line with 2 number are NOT right) 
http://supervisord.org/running.html#signals

When you do this: 
        ` ps -ef | grep supervisord`
//You will get some pid of supervisord just like these

//root 2641 12938 0 04:52 pts/1 00:00:00 grep --color=auto supervisord

//root 29646 1 0 04:45 ? 00:00:00 /usr/bin/python /usr/local/bin/supervisord

if you get output like that, your pid is the second one ( with only one number, it will not change if you run again again, but other number are changing. then if you want to shut down your supervisord you can do this

        kill -s SIGTERM 29646

Here is full  supervisord.conf

                         [unix_http_server]
                            file=/tmp/supervisor.sock                       ; path to your socket file

                  [supervisord]
                  ;logfile=/var/log/supervisord/supervisord.log    ; supervisord log file
                  ;logfile_maxbytes=50MB                           ; maximum size of logfile before rotation
                  ;logfile_backups=10                              ; number of backed up logfiles
                  ;loglevel=error                                  ; info, debug, warn, trace
                    ;pidfile=/var/run/supervisord.pid                ; pidfile location
                 nodaemon=false                                  ; run supervisord as a daemon
                    minfds=1024                                     ; number of startup file descriptors
                    minprocs=200                                    ; number of process descriptors
                   user=root                                       ; default user
                       ;childlogdir=/var/log/supervisord/               ; where child log files will

                       [program:fileRestAPI]
                      command=./gohttpserver -r ./fileRestAPI --cors
                          ;command=gohttpserver -r ./fileRestAPI --port 8000 --upload --delete --cors

                          [supervisorctl]
                              serverurl=unix:///tmp/supervisor.sock         ; use a unix:// URL  for a unix socket

**Comment by rmasci** [comment]
I used start-stop-daemon. 

`#! /bin/sh

### BEGIN INIT INFO
# Provides:          sdn-chatbot
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: sdn-chatbot
# Description:       sdn-chatbot
### END INIT INFO

# Installation
# - Move this to /etc/init.d/myservice
# - chmod +x this
#
# Starting and stopping
# - Start: `service myservice start` or `/etc/init.d/myservice start`
# - Stop: `service myservice stop` or `/etc/init.d/myservice stop`

#ref http://till.klampaeckel.de/blog/archives/94-start-stop-daemon,-Gearman-and-a-little-PHP.html
#ref http://unix.stackexchange.com/questions/85033/use-start-stop-daemon-for-a-php-server/85570#85570
#ref http://serverfault.com/questions/229759/launching-a-php-daemon-from-an-lsb-init-script-w-start-stop-daemon

NAME="HttpFS"
DESC="HTTP File Server"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"
USERNAME="root"
DAEMON="/usr/local/sbin/gohttpserver"
DAEMON_OPTS="-r /var/www/html/ --port=8000 --upload --title=fileserver"

#START_OPTS="--start --background --no-close --make-pidfile --chuid ${USERNAME} --pidfile ${PIDFILE} --startas /bin/bash -- -c \"exec ${DAEMON} ${DAEMON_OPTS}\" >> /var/log/gohttpd.log 2>&1"
STOP_OPTS="--stop --pidfile ${PIDFILE}"

test -x $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "Starting ${DESC}: "
        start-stop-daemon --start --background --no-close --make-pidfile --chuid ${USERNAME} --pidfile ${PIDFILE} --startas /bin/bash -- -c "exec ${DAEMON} ${DAEMON_OPTS}" >> /var/log/gohttpd.log 2>&1
        #start-stop-daemon $START_OPTS 2>&1 >> $LOGFILE
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon $STOP_OPTS
        echo "$NAME."
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --start --background --no-close --make-pidfile --chuid ${USERNAME} --pidfile ${PIDFILE} --startas /bin/bash -- -c "exec ${DAEMON} ${DAEMON_OPTS}" >> /var/log/gohttpd.log 2>&1
        sleep 1
        start-stop-daemon $START_OPTS 2>&1 >> $LOGFILE
        echo "$NAME."
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0`
